workspace 1 output eDP-1
workspace 2 output eDP-1
workspace 3 output eDP-1
workspace 4 output eDP-1
workspace 5 output eDP-1
workspace 6 output "AOC Q27G3XMN 1APRAJA000656"
workspace 7 output "AOC Q27G3XMN 1APRAJA000656"
workspace 8 output "AOC Q27G3XMN 1APRAJA000656"
workspace 9 output "AOC Q27G3XMN 1APRAJA000656"
workspace 10 output "AOC Q27G3XMN 1APRAJA000656"
